### ISSUE TITLE
Minitest::Reporters issue blocking update of Minitest to 5.10.0

### ISSUE THREAD

**Issue by jdickey** [TheProlog/prolog-dry_types#7]
When issue kern/minitest-reporters#219 is resolved and a new build of their Gem pushed, we should update `minitest` to 5.10.0 or whatever the current build on RubyGems is.

(expression of intense frustration redacted)

**Comment by zenspider** [comment]
I just released minitest 5.10.1 to patch this up until this gets fixed properly in minitest-reporters.

Is that second paragraph really necessary? Does pretending to quote me with something I've never said honest or fair or even remotely accurate? Does it make you feel better?

**Comment by jdickey** [comment]
@zenspider Apologies. That was written at the very end of a long, stressful day and the wording was less than professional. It does, however, express my experience in trying to follow how you folks do releases. I've looked at your repos for years; while you have great tools and perform an unreservedly important service to the community, people who are familiar with community standards (SemVer, GitHub issues and release tagging, etc.) find them incomprehensible. Many people, likely including yourselves, have jobs that soak up most of their available cognitive resources, and GitHub has some great resources to help projects help people figure out productive ways to contribute without totally immersing themselves in the innermost lore and arcana of projects. People can actually propose bugfixes if the walls to such contribution are not unduly raised; that would tend to reduce *your* workload, wouldn't it?

Second paragraph is gone. Thanks for the fix, and the feedback.
